export enum DataTypes{
    // STRING
    CHAR = 'CHAR',
    VARCHAR = 'VARCHAR',
    BINARY = 'BINARY',
    VARBINARY = 'VARBINARY',
    TINYBINARY = 'TINYBINARY',
    TINYTEXT = 'TINYTEXT',
    TEXT = 'TEXT',
    BLOB = 'BLOB',
    MEDIUMTEXT = 'MEDIUMTEXT',
    MEDIUMBLOB = 'MEDIUMBLOB',
    LONGTEXT = 'LONGTEXT',
    LONGBLOB = 'LONGBLOB',

    // NUMERIC
    BIT = 'BIT',
    TINYINT = 'TINYINT',
    BOOLEAN = 'BOOLEAN',
    SMALLINT = 'SMALLINT',
    MEDIUMINT = 'MEDIUMINT',
    INT = 'INT',
    BIGINT = 'BIGINT',
    FLOAT = 'FLOAT',
    DOUBLE = 'DOUBLE',
    DECIMAL = 'DECIMAL',

    // DATE AND TIME
    DATE = 'DATE',
    DATETIME = 'DATETIME',
    TIME = 'TIME',
    YEAR = 'YEAR'    
}